### 주석

### 1-1. 문자열 응답
GET localhost:8080/reponsec/hello

### 1-2. Object 응답
GET localhost:8080/reponsec/message

### 1-3. List 응답
GET localhost:8080/reponsec/list

### 1-4. Map 응답
// GET localhost:8080/reponsec/Map
GET {{baseUrl}}/response/map

### 1-5. File 응답
//GET localhost:8080/reponsec/image
GET {{baseUrl}}/response/image